version: 3.8

services:
  app:
    build: .
    container_name: nan-fastapi-poc
    command: uvicorn main:app --host 127.0.0.1 --port 5000 ---reload
    ports:
      - 5000:5000
    volumes:
      - .:app
  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
volumes:
  db:
    driver: local